# Defaults: https://docs.netlify.com/routing/redirects/redirect-options/
[[redirects]]
  from = "https://endangeredlanguagealliance.org/*"
  to = "/"
[[redirects]]
  from = "https://endangeredlanguagealliance.org/"
  to = "/"
[[redirects]]
  from = "https://endangeredlanguagealliance.org"
  to = "/"
[build]
  publish = ".next"
[[plugins]]
  package = "@netlify/plugin-nextjs"
